apiVersion: rds.nomsmon.com/v1alpha1
kind: SubnetGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ include "aurora-db.name" . }}
spec:
  name: test-subnet-group-k8s
  description: "test subnet group created by k8s"
  subnets:
  {{- range .Values.subnets }}
  - {{ . }}
  {{- end }}
  region: {{ .Values.aws.region }}
---
apiVersion: rds.nomsmon.com/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ include "aurora-db.name" . }}
spec:
  id: test-cluster-k8s
  engine: aurora-mysql
  engine_version: 5.7.12
  master_username: admin
  master_user_pass: hello-world-123456
  subnet_group_name: test-subnet-group-k8s
  #cluster_parameter_group_name: test-cluster-parameter-group-k8s
  security_group_ids:
  {{- range .Values.security_group_ids }}
  - {{ . }}
  {{- end }}
---
apiVersion: rds.nomsmon.com/v1alpha1
kind: ParameterGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ include "aurora-db.name" . }}
spec:
  name: test-parameter-group-k8s
  family: "aurora-mysql5.7"
  description: "test parameter group created by k8s"
  parameters:
  {{- range .Values.db_parameters }}
  - name: {{ .name }}
    value: "{{ .value }}"
  {{- end }}
---
apiVersion: rds.nomsmon.com/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ include "aurora-db.name" . }}
spec:
  id: test-cluster-primary-k8s
  cluster_id: test-cluster-k8s
  engine: aurora-mysql
  allocated_storage: 10
  class: db.t2.small
  parameter_group_name: test-parameter-group-k8s
---
apiVersion: rds.nomsmon.com/v1alpha1
kind: ClusterService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterservice-sample
spec:
  cluster_name: {{ include "aurora-db.name" . }}
