apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusterdeletions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusterparametergroups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusterservices
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instancedeletions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - parametergroups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - parametergroupdeletions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - subnetgroups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - subnetgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - subnetgroupdeletions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
