apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instances
  - instances/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusterdeletions
  - clusterdeletions/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusterparametergroups
  - clusterparametergroups/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusterservices
  - clusterservices/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instances
  - instances/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instances
  - instances/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instancedeletions
  - instancedeletions/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - parametergroups
  - parametergroups/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - parametergroupdeletions
  - parametergroupdeletions/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - subnetgroups
  - subnetgroups/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rds.nomsmon.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - subnetgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.nomsmon.com
  resources:
  - subnetgroupdeletions
  - subnetgroupdeletions/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
