apiVersion: rds.nomsmon.com/v1alpha1
kind: ParameterGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: parametergroup-sample
spec:
  name: test-parameter-group-k8s
  family: "MySQL5.7"
  description: "test parameter group created by k8s"
  parameters:
  - name: "wait_timeout"
    value: "666"
