apiVersion: rds.nomsmon.com/v1alpha1
kind: DatabaseRestore
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: databaserestore-sample
spec:
  filepath: /Users/cwippern/Code/src/github.com/datacharmer/test_db/employees.sql
